{% set version = "0.7" %}

package:
  name: pygeoif
  version: {{ version }}

source:
  fn: pygeoif-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/p/pygeoif/pygeoif-{{ version }}.tar.gz
  sha256: 11aa0c071d38befa4af3bd123efa834abe0823a873f3744f0a070a44025afe04

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - pygeoif
  requires:
    - pytest

about:
  home: https://github.com/cleder/pygeoif/
  license: LGPL-2.1
  summary: 'A basic implementation of the __geo_interface__'

extra:
  recipe-maintainers:
    - benjwadams
    - daf
    - kwilcox
    - lukecampbell
    - ocefpaf
