travis:
  secure:
    BINSTAR_TOKEN: Hr2MR8kZgE8CeBGd4smWnXyKRSqBtl5l55kCkgMSmSnpAATiiT8XijtHeQdLcFeynqET4TfsDMzc7euSihtgl3kMt8VsE2tEunAlg9JAKwvqR3ldjdxBk/Ow2JpXWweJj3Dz9oxEM3x8DRErzwGsMqZGZPqVdOI6y/jRxUuPwAQDqXF2EB+l1iRcSbdcmTe1OzvZZlFdhYrHh3tG/kkgWJNA0g/zhzGUEPPHmIpCBqrFGYjRHaKn7RxYG2QqdzR/ODsymlufMD8O6CyqCrJ76Jl3Y8yH+35XRp3R1k8mBc54cAuUBf1p6Vjzzaf03hsPB40lKPHPXQ9y9QNyF5I9CPAmksdNiaR6iq6WkbiOVu2GfGLiWw/ibFA4t0DeSJI9gvlkT17H0RQTDYsMWbT5EwHObfmRm67XyRaLfRl4ZQXyZsgPc6gz+05V2hrZR+yQW90kntJXQd3XXZT/gnd83qUyippzcUOvTWA9FWmqktg9HmteismfFwl4zDUb6d9/vUBZ057xCiA8yHpv7yGRP2cdDWlmpm4SOlv0U9FdFypt5fii5IXFTQla4PwgZ5oVdOMLhmoJQEOPDAndhLzGtKF+tgrdPOUjhBpqXyEm4iMYF4A4fog4XbMrl66ZeMtAWe4npg3xGkLz7NwLK7gWkUbvy9cq+EdZvSxbANIw7tk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
