travis:
  secure:
    BINSTAR_TOKEN: ThiJmn39zY6YVEyR2Ik8W/K4JKJm0ceQoOVK4CuqtsfkAqGsScHyL3Ity/jUTJKyzgFUsTAPH8pwBybPoGfECJqGd+3368RoEDrSrutKlTlFt+CdunFN3ZJZA8fPbCJoZbaV3B6Uu8eNmwIH8XQt3zlR4dkatf99gOKZGoHBqFdDk4pzP/MTclj/lvC8CS7TiQx8hYVM/p2rbsvFBvICaRR+3I39vunyXQr201mJvz2jpiDu0nNKzbYLPRfR0moRUPFKEvWzu5Ef8vHHrlfxunU4ls1jMe+diGhXnvAU8PsiXj4N6EjDHR7jG30t9dVPXp4+o8YyV1nT6TYE+DCOivWc2iBRoiOit1igClcAS6QRPgZjLIc4J8ht1EuN1S7HBXdWB3tkVeqYVHDAnN3wKzZJ9dgJTBylV7PY1KVKwWaECKc+i2RU0J4IQX5nLnKUN7aIMTTodnCUjFRvVX7IjuFkpRI5uqBZKPW/xoM8DTJGJYOw+Im9VWGsKtZjLjBwHOtY/DYz49uwushe1v6JoHu4SG70zj9NMc3mY/V0ZVTgw8bHSfOay4l77g4m6GeHIVT9tpshw3j62EHgpEPkcA8EWVTW3EpqUIttE5Gk5ZZBAMqcebz2YWIlh04c8XJbqsrEKbrxJbHrwFXFFIE8xne/GAGnXKTLwA+NT42NXOk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
